services:
  - type: web
    name: duel-masters-ai-bot
    env: docker
    plan: free
    region: singapore # Opsional, bisa dihapus atau diganti
    branch: main
    envVars:
      - key: PORT
        value: 8080